In [1]:
import numpy as np
X = np.array(([0,0],[0,1],[1,0],[1,1]),dtype=float)
y = np.array(([0],[1],[1],[0]),dtype=float)
print(X)
print("_____________________")
print(y)
print("_____________________")
X = X/np.amax(X, axis=0)
print(X)
print("_____________________")
y = y/100
print(y)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
_____________________
[[0.]
 [1.]
 [1.]
 [0.]]
_____________________
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
_____________________
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]


In [11]:
class Neural_Network():
    def __init__(self):
        np.random.seed(0)
        
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.w1 = np.random.randn(self.inputSize,self.hiddenSize)
        print("w1",self.w1)
        self.w2 = np.random.randn(self.hiddenSize,self.outputSize)
        print("w2",self.w2)
    def forward(self,X):
        self.z = np.dot(X,self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2,self.w2)
        o = self.sigmoid(self.z3)
        return o
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    def sigmoidPrime(self,s):
        return s*(1-s)
    def backward(self,X,y,o):
        self.o_error = y-o
        self.o_delta = self.o_error*self.sigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2)
        self.w1 += X.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.o_delta)
        print("\nHello")
        print(self.z2_error)
        print("\nBye")
        print(self.z2_delta)
        print("\nHi")
        print(self.w1)
        print("\nGood")
        print(self.w2)
        
    def train(self,X,y):
        o = self.forward(X)
        self.backward(X,y,o)
        
NN = Neural_Network()
for i in range(1100):
    print("Input:\n"+str(X))
    print("Actual output:\n"+str(y))
    print("Predicted output:\n"+str(NN.forward(X)))
    print("Loss:\n"+str(np.mean(np.square(y-NN.forward(X)))))
    print("\n")
    NN.train(X,y)

w1 [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]
w2 [[ 0.95008842]
 [-0.15135721]
 [-0.10321885]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.58607335]
 [0.66805998]
 [0.6559865 ]
 [0.6779312 ]]
Loss:
0.41335354178881223



Hello
[[-0.1350801   0.02151941  0.01467528]
 [-0.13864512  0.02208735  0.01506259]
 [-0.13850258  0.02206464  0.0150471 ]
 [-0.14063193  0.02240387  0.01527844]]

Bye
[[-0.03377002  0.00537985  0.00366882]
 [-0.01204762  0.00256027  0.00299244]
 [-0.01729685  0.0053011   0.00298738]
 [-0.00247212  0.00190495  0.00381961]]

Hi
[[ 1.74428337  0.40736326  0.98554498]
 [ 2.22637345  1.87202321 -0.97046583]]

Good
[[ 0.47727686]
 [-0.57025735]
 [-0.39423288]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.43939773]
 [0.45716   ]
 [0.44442439]
 [0.43844557]]
Loss:
0.1934953729129258



Hello
[[-0.0516583

Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.06217645]
 [0.0218143 ]
 [0.01865834]
 [0.01103188]]
Loss:
0.001050539563157279



Hello
[[0.00503054 0.00830958 0.00633632]
 [0.00034979 0.0005778  0.00044059]
 [0.00021997 0.00036336 0.00027707]
 [0.000167   0.00027586 0.00021035]]

Bye
[[1.25763454e-03 2.07739595e-03 1.58407953e-03]
 [3.04427855e-05 6.20398557e-05 9.38461430e-05]
 [2.75981019e-05 8.40363073e-05 5.12421756e-05]
 [2.95968700e-06 1.88180326e-05 5.13072006e-05]]

Hi
[[ 1.75756254  0.56173856  1.12591029]
 [ 2.23900009  1.97053837 -0.81098749]]

Good
[[-1.38982091]
 [-2.2942023 ]
 [-1.74976776]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.06198372]
 [0.0217129 ]
 [0.01856609]
 [0.01097017]]
Loss:
0.0010432241322168262



Hello
[[0.00500869 0.00826794 0.00630589]
 [0.00034579 0.0005708  0.00043534]
 [0.00021693 0.00035809 0.00027311]
 [0.000

[[8.60033449e-04 1.35153152e-03 1.04882774e-03]
 [9.53878424e-06 1.84514406e-05 2.86324273e-05]
 [5.59645538e-06 1.62057727e-05 1.00388094e-05]
 [1.31984785e-06 7.93585241e-06 2.21805176e-05]]

Hi
[[ 1.7593844   0.56787823  1.13264504]
 [ 2.24124543  1.97593819 -0.80102183]]

Good
[[-1.57893312]
 [-2.48056324]
 [-1.92520835]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.04777257]
 [0.01474237]
 [0.01229243]
 [0.00688712]]
Loss:
0.0005893489487598884



Hello
[[3.43132276e-03 5.39073694e-03 4.18384487e-03]
 [1.08761734e-04 1.70868770e-04 1.32614230e-04]
 [4.39465821e-05 6.90417313e-05 5.35844906e-05]
 [7.43768036e-05 1.16848752e-04 9.06883527e-05]]

Bye
[[8.57830690e-04 1.34768424e-03 1.04596122e-03]
 [9.44820617e-06 1.82707969e-05 2.83564519e-05]
 [5.50639277e-06 1.59403863e-05 9.87544061e-06]
 [1.31289822e-06 7.89160252e-06 2.20600030e-05]]

Hi
[[ 1.75939122  0.56790207  1.13267698]
 [ 2.2412562   1.97596435 -0.80097

[[-1.69493547]
 [-2.5960041 ]
 [-2.03674981]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.04054921]
 [0.01159718]
 [0.00951681]
 [0.00516452]]
Loss:
0.00041842381177184323



Hello
[[ 2.67387253e-03  4.09536774e-03  3.21310720e-03]
 [ 3.10308910e-05  4.75276621e-05  3.72888304e-05]
 [-7.71983256e-06 -1.18238820e-05 -9.27667619e-06]
 [ 4.49742393e-05  6.88836312e-05  5.40441067e-05]]

Bye
[[ 6.68468131e-04  1.02384193e-03  8.03276799e-04]
 [ 2.69400325e-06  5.07461469e-06  7.98517973e-06]
 [-9.67053752e-07 -2.72892685e-06 -1.70761180e-06]
 [ 7.93049534e-07  4.63934771e-06  1.31326597e-05]]

Hi
[[ 1.7597081   0.56917232  1.13499289]
 [ 2.24201669  1.97788982 -0.79709277]]

Good
[[-1.69576298]
 [-2.59683067]
 [-2.03755632]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.04050137]
 [0.01157729]
 [0.00949939]
 [0.0051539 ]]
Loss:
0.00041741561279824203





Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.03562777]
 [0.00961689]
 [0.00779293]
 [0.00412728]]
Loss:
0.0003228475315856681



Hello
[[ 2.18505906e-03  3.28825904e-03  2.60180037e-03]
 [-6.51327980e-06 -9.80172642e-06 -7.75551291e-06]
 [-3.04621208e-05 -4.58419388e-05 -3.62719518e-05]
 [ 3.02812025e-05  4.55696779e-05  3.60565282e-05]]

Bye
[[ 5.46264766e-04  8.22064759e-04  6.50450092e-04]
 [-5.65373695e-07 -1.04600383e-06 -1.66185833e-06]
 [-3.81661218e-06 -1.05814997e-05 -6.67409802e-06]
 [ 5.33987448e-07  3.06848170e-06  8.75805786e-06]]

Hi
[[ 1.75945996  0.56872706  1.13576845]
 [ 2.24220699  1.97856933 -0.79541773]]

Good
[[-1.78562345]
 [-2.68684944]
 [-2.12606369]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.0355963 ]
 [0.00960467]
 [0.00778236]
 [0.00412101]]
Loss:
0.00032228836801636483



Hello
[[ 2.18201866e-03  3.28331016e-03  2.5980

 [0.00349295]]
Loss:
0.00026760007245152606



Hello
[[ 1.87228101e-03  2.78383851e-03  2.21665409e-03]
 [-2.51298642e-05 -3.73648418e-05 -2.97520596e-05]
 [-4.05859393e-05 -6.03460165e-05 -4.80510071e-05]
 [ 2.25166876e-05  3.34793879e-05  2.66582352e-05]]

Bye
[[ 4.68070253e-04  6.95959628e-04  5.54163522e-04]
 [-2.18156703e-06 -3.98744690e-06 -6.37627294e-06]
 [-5.08682365e-06 -1.39340709e-05 -8.84166098e-06]
 [ 3.97303442e-07  2.25670474e-06  6.47483729e-06]]

Hi
[[ 1.75895911  0.56751476  1.13572049]
 [ 2.24208395  1.97856234 -0.79502021]]

Good
[[-1.85247676]
 [-2.75415972]
 [-2.19312304]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.03229922]
 [0.00835551]
 [0.00670653]
 [0.00348872]]
Loss:
0.0002672405711203369



Hello
[[ 1.87015672e-03  2.78044530e-03  2.21405411e-03]
 [-2.52413817e-05 -3.75274864e-05 -2.98829420e-05]
 [-4.06426615e-05 -6.04252551e-05 -4.81163159e-05]
 [ 2.24681642e-05  3.34044205e-05  2.659

[[ 1.65322556e-03  2.43629376e-03  1.94966202e-03]
 [-3.55369004e-05 -5.23693385e-05 -4.19089488e-05]
 [-4.55637560e-05 -6.71455230e-05 -5.37336992e-05]
 [ 1.78051700e-05  2.62387818e-05  2.09977784e-05]]

Bye
[[ 4.13306389e-04  6.09073441e-04  4.87415506e-04]
 [-3.08570631e-06 -5.59011160e-06 -8.98083933e-06]
 [-5.71315327e-06 -1.55106206e-05 -9.88952934e-06]
 [ 3.14435966e-07  1.77146466e-06  5.10059124e-06]]

Hi
[[ 1.7583542   0.56598861  1.13528096]
 [ 2.24180758  1.97822073 -0.79526613]]

Good
[[-1.90524638]
 [-2.80749984]
 [-2.24680905]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.02989313]
 [0.00748426]
 [0.00596228]
 [0.00305894]]
Loss:
0.0002313970728356095



Hello
[[ 1.65163257e-03  2.43378402e-03  1.94772868e-03]
 [-3.56043804e-05 -5.24652841e-05 -4.19873487e-05]
 [-4.55934476e-05 -6.71848001e-05 -5.37672039e-05]
 [ 1.77730486e-05  2.61897000e-05  2.09593084e-05]]

Bye
[[ 4.12908143e-04  6.08446005e-04  4

 [ 1.46365114e-05  2.14173780e-05  1.72113468e-05]]

Bye
[[ 3.72013436e-04  5.44361438e-04  4.37457541e-04]
 [-3.63796585e-06 -6.54488008e-06 -1.05522250e-05]
 [-6.03800289e-06 -1.62771071e-05 -1.04204675e-05]
 [ 2.58731843e-07  1.44868047e-06  4.18171065e-06]]

Hi
[[ 1.75769789  0.56431038  1.13462853]
 [ 2.24144487  1.97769305 -0.79587726]]

Good
[[-1.94919216]
 [-2.85206631]
 [-2.29204223]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.02801364]
 [0.00682806]
 [0.00540546]
 [0.00274189]]
Loss:
0.00020586320306266483



Hello
[[ 1.48680434e-03  2.17549847e-03  1.74832343e-03]
 [-4.19277616e-05 -6.13488801e-05 -4.93025788e-05]
 [-4.81476805e-05 -7.04498921e-05 -5.66165405e-05]
 [ 1.46137803e-05  2.13829459e-05  1.71842481e-05]]

Bye
[[ 3.71701084e-04  5.43874616e-04  4.37080857e-04]
 [-3.64170656e-06 -6.55125870e-06 -1.05627942e-05]
 [-6.03996740e-06 -1.62815120e-05 -1.04236250e-05]
 [ 2.58332304e-07  1.44637608e-06  

 [0.00246763]]
Loss:
0.0001844563044065245



Hello
[[ 1.34160542e-03  1.95031261e-03  1.57371521e-03]
 [-4.63863215e-05 -6.74325151e-05 -5.44115719e-05]
 [-4.95307536e-05 -7.20036249e-05 -5.81000191e-05]
 [ 1.20970940e-05  1.75857332e-05  1.41899999e-05]]

Bye
[[ 3.35401354e-04  4.87578151e-04  3.93428802e-04]
 [-4.03050373e-06 -7.20490318e-06 -1.16531179e-05]
 [-6.21686219e-06 -1.66496769e-05 -1.07016296e-05]
 [ 2.14101282e-07  1.19229378e-06  3.44871302e-06]]

Hi
[[ 1.75691839  0.56230605  1.1337321 ]
 [ 2.24096752  1.97695475 -0.79684884]]

Good
[[-1.99186119]
 [-2.89546879]
 [-2.33643287]]
Input:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual output:
[[0.  ]
 [0.01]
 [0.01]
 [0.  ]]
Predicted output:
[[0.02629111]
 [0.00624591]
 [0.00491443]
 [0.00246579]]
Loss:
0.00018431473427683298



Hello
[[ 1.34062134e-03  1.94879405e-03  1.57253517e-03]
 [-4.64128762e-05 -6.74680720e-05 -5.44418306e-05]
 [-4.95372949e-05 -7.20098829e-05 -5.81067419e-05]
 [ 1.20808779e-05  1.75613668e-05  1.417

In [22]:
import numpy as np
s=1.1760349
a=1/(1+np.exp(-s))
print(a)

0.7642341194093673
